### ISSUE TITLE
Running the pipeline with Python 3.11

### ISSUE THREAD

**Issue by AinaIanemahy** [Garrafao/WUGs#35]
When running the pipeline in an environment with python 3.11 the following error occurs:

```
Traceback (most recent call last):
  File "/home/arbeit/Desktop/DURel/durel_system/WUGs/scripts/data2join.py", line 46, in <module>
    w = csv.DictWriter(f, ['identifier1', 'identifier2', 'judgment', 'comment', 'annotator', 'lemma'], delimiter='\t', quoting = csv.QUOTE_NONE, quotechar='')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/csv.py", line 139, in __init__
    self.writer = writer(f, dialect, *args, **kwds)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: "quotechar" must be a 1-character string
```

This error (and comparable ones) occur in three scripts: data2join, data2agr and data2annotator. I was able to 'solve' it by removing `quotechar=0` in all three files. It should be tested whether this change breaks anything in the pipeline.

**Comment by Garrafao** [comment]
solved with last commit with above-proposed solution.
